name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn install
    - run: yarn tsc --noEmit
    - run: yarn eslint src
    - run: yarn prettier src --check
    - run: yarn test
